### ISSUE TITLE
API for PlanningScene change for Kinetic

### ISSUE THREAD

**Issue by mgvargas** [SemRoCo/knowrob_moveit#2]
The package does not longer compiles due to a change in the pointer's definition in the `planning_scene.h`, from `‘boost::shared_ptr` to `aka const std::shared_ptr`. The compiling error is:

`In file included from /home/mine/obj_grasp_ws/src/knowrob_moveit/include/knowrob_moveit/knowrob_moveit.hpp:34:0,
                 from /home/mine/obj_grasp_ws/src/knowrob_moveit/src/knowrob_moveit/planning_scene_server.cpp:32:
/home/mine/obj_grasp_ws/src/knowrob_moveit/include/knowrob_moveit/planning_scene.hpp: In member function ‘void knowrob_moveit::PlanningScene::createPlanningScene(const string&, const string&)’:
/home/mine/obj_grasp_ws/src/knowrob_moveit/include/knowrob_moveit/planning_scene.hpp:99:118: error: no matching function for call to ‘planning_scene::PlanningScene::PlanningScene(boost::shared_ptr<const urdf::Model>&, boost::shared_ptr<const srdf::Model>&)’
           ps_ptr_ = planning_scene::PlanningScenePtr(new planning_scene::PlanningScene(urdf_const_ptr, srdf_const_ptr));
                                                                                                                      ^
In file included from /home/mine/obj_grasp_ws/src/knowrob_moveit/include/knowrob_moveit/planning_scene.hpp:34:0,
                 from /home/mine/obj_grasp_ws/src/knowrob_moveit/include/knowrob_moveit/knowrob_moveit.hpp:34,
                 from /home/mine/obj_grasp_ws/src/knowrob_moveit/src/knowrob_moveit/planning_scene_server.cpp:32:
/opt/ros/kinetic/include/moveit/planning_scene/planning_scene.h:930:3: note: candidate: planning_scene::PlanningScene::PlanningScene(const PlanningSceneConstPtr&)
   PlanningScene(const PlanningSceneConstPtr& parent);
   ^
/opt/ros/kinetic/include/moveit/planning_scene/planning_scene.h:930:3: note:   candidate expects 1 argument, 2 provided
/opt/ros/kinetic/include/moveit/planning_scene/planning_scene.h:95:3: note: candidate: planning_scene::PlanningScene::PlanningScene(const ModelInterfaceSharedPtr&, const ModelConstSharedPtr&, collision_detection::WorldPtr)
   PlanningScene(const urdf::ModelInterfaceSharedPtr& urdf_model, const srdf::ModelConstSharedPtr& srdf_model,
   ^
/opt/ros/kinetic/include/moveit/planning_scene/planning_scene.h:95:3: note:   no known conversion for argument 1 from ‘boost::shared_ptr<const urdf::Model>’ to ‘const ModelInterfaceSharedPtr& {aka const boost::shared_ptr<urdf::ModelInterface>&}’
/opt/ros/kinetic/include/moveit/planning_scene/planning_scene.h:90:3: note: candidate: planning_scene::PlanningScene::PlanningScene(const RobotModelConstPtr&, collision_detection::WorldPtr)
   PlanningScene(const robot_model::RobotModelConstPtr& robot_model,
   ^
/opt/ros/kinetic/include/moveit/planning_scene/planning_scene.h:90:3: note:   no known conversion for argument 1 from ‘boost::shared_ptr<const urdf::Model>’ to ‘const RobotModelConstPtr& {aka const std::shared_ptr<const moveit::core::RobotModel>&}’
knowrob_moveit/CMakeFiles/planning_scene_server.dir/build.make:62: recipe for target 'knowrob_moveit/CMakeFiles/planning_scene_server.dir/src/knowrob_moveit/planning_scene_server.cpp.o' failed
make[2]: *** [knowrob_moveit/CMakeFiles/planning_scene_server.dir/src/knowrob_moveit/planning_scene_server.cpp.o] Error 1
CMakeFiles/Makefile2:13315: recipe for target 'knowrob_moveit/CMakeFiles/planning_scene_server.dir/all' failed
make[1]: *** [knowrob_moveit/CMakeFiles/planning_scene_server.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j4 -l4" failed
`

**Comment by amaldo** [comment]
Fixed in this pull request: [https://github.com/SemRoCo/knowrob_moveit/pull/3](url)

**Comment by airballking** [comment]
Merged.
